name: PHP Composer

on:
  push:
    branches: [ debug_action ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Install Composer dependencies
      run: composer install

    - name: Install NPM dependencies
      run: |
          chmod +x ./builder.sh
          cd ./modules/AdminPanelWebclient/vue
          npm install
          npm install -g @quasar/cli
          
    - name: Compile static files
      run: |
          cd ./modules/AdminPanelWebclient/vue
          ln -s /usr/bin/nodejs /usr/bin/node
          npm run build-production
